### ISSUE TITLE
Consider adding JSDoc to the APIs 

### ISSUE THREAD

**Issue by thomscoder** [nearform/lyra#32]
**Is your feature request related to a problem? Please describe.**
I've started working on the docusaurus docs as in #24. 
I think these two issuses can be related to each other 🙂

**Describe the solution you'd like**
I'd like to add some JSDoc to current or future APIs. 
While it is true they're quite intuitive, I think it would ease the end-user in the usage of Lyra's methods.

**Additional context**
Before:
<img width="907" alt="Screenshot 2022-07-19 111205" src="https://user-images.githubusercontent.com/78874117/179713722-38a007a4-0c4b-4269-ab20-d99beacf077c.png">

After (merely an example):
<img width="902" alt="Screenshot 2022-07-19 111608" src="https://user-images.githubusercontent.com/78874117/179714705-8f60227e-292e-4202-8c1b-1bedc4adeb3c.png">

**Comment by thomscoder** [comment]
I quickly worked on #32 in https://github.com/thomscoder/lyra/tree/api_docs

I've based the docs on https://nearform.github.io/lyra/
and tried to be as more concized as possible.

I also put the code examples 👍🏽

**Comment by mateonunez** [comment]
I'm not sure it's a good deal to mix TypeScript and JSDocs.

JSDocs [can be used](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) with TypeScript, of course. But it probably requires too much effort to modify an existing API or to create a new one.

Instead of JSDocs, Microsoft has created a standard to the doc comments: [TSDoc](https://github.com/microsoft/tsdoc).

**Comment by thomscoder** [comment]
> Instead of JSDocs, Microsoft has created a standard to the doc comments: [TSDoc](https://github.com/microsoft/tsdoc).

Oh, alright @mateonunez , I might consider migrating to TSDoc then. 👍🏽 
I think I might commit the changes in conjuction with #24 .

**Comment by micheleriva** [comment]
Closing this, I'd prefer avoiding JSDoc/TSDocs
