### ISSUE TITLE
Consider Dependency Injection

### ISSUE THREAD

**Issue by simonireilly** [nearform/lyra#35]
Currently the natural language processing from `natural` includes a great deal of large dependencies. For example when I bundle Lyra with esbuild to deploy to lambda it is 13.1 MB in size.

Is it possible to allow injection of both the stemmer, and word tokenizer, so long as those injected dependencies fulfill the contract of the function interface?

This would mean a smaller, but likely less accurate, dependency could be used, making Lyra a lot smaller - possibly allowing for FE deployment - as at 13.1 MB I would not deploy into my browser.

## Follow Up

- [ ] Create example web app with bundled size
- [ ] Create example edge function with bundled size

**Comment by micheleriva** [comment]
I do agree with you. Also, yesterday I released a feature where you can disable stemming entirely, so it might be worth it to avoid Natural import directly when stemming is disabled.

Also, I am considering using a different library because of #31.

I'll keep you posted, thanks for opening the issue!

**Comment by micheleriva** [comment]
Update: we're moving to a different library (#37)

**Comment by micheleriva** [comment]
I'm going to close this issue for two reasons:

1. We will adopt dependency injection
2. We removed the library 

Cheers!
