### ISSUE TITLE
How does insert work? Why storing individual tokens?

### ISSUE THREAD

**Issue by nasainsbury** [nearform/lyra#85]
Hi,

Apologies, I'm just exploring the code and had a question about `insert(nodes: Nodes, node: Node, word: string, docId: string)`. Looking through the code it looks like `word` is being looped across, and the parameter, `word` implied to me it takes a single word.

However, I was checking out the test:

```js
const phrases = [
  { id: "1", doc: "the quick, brown fox" },
  { id: "2", doc: "jumps over the lazy dog" },
  { id: "3", doc: "just in time!" },
  { id: "4", doc: "there is something wrong in there" },
  { id: "5", doc: "this is me" },
  { id: "6", doc: "thought it was sunday" },
  { id: "7", doc: "let's try this trie" },
];

t.test("trie", t => {
  t.plan(3);

  t.test("should correctly index phrases into a prefix tree", t => {
    t.plan(phrases.length);

    const nodes = {};
    const trie = createNode();

    for (const { doc, id } of phrases) {
      trieInsert(nodes, trie, doc, id);
    }
...
```

It looks like from this code that `word` can be any string, i.e a phrase.

The purpose of this issue isn't a "gotcha", but just me trying to get used to libraries that I'm not familiar with and taking small steps to investigate the code.

I've added a few `console.logs` and reran the tests to check and it does seem that i.e `the quick, brown fox` is passed in as `word`, is this assumption correct? As far as I can see, it shouldn't matter if you passed in `h`, `hello` or `hello world`, as the function loops over each character anyway.

P.S I don't think there's anything wrong with this, just wanted to see if my testing was correct. Although, would be interested in your thoughts on renaming the parameter to `phrase`? This is really not crucial, or important whatsoever, so apologies again if it's distracted you from more important features/issues.

**Comment by micheleriva** [comment]
Hi @nasainsbury,
no need to apologize, let me explain 🙂

We have to distinguish two different data structures: the trie, which is the radix tree itself, and the index, which is a radix tree used as an inverted index to store the reference of a token with a document.

When inserting something in a trie, we can technically insert whatever we want, as long as it's a string. So yes, you could also insert a phrase.

Things change when we want to index the individual tokens; here, we split the sentence into multiple tokens and insert them individually in the prefix tree.

The reasoning behind the indexing procedure is the following:

1. Take a document, let's say `hello, world` and give it an id, let's say `1`
2. Insert the entire document as is in a `docs` index (an hashmap like this: `{ 1: 'hello, world' }`
3. Break down the document into individual tokens: `['hello', 'world']`
4. Now insert individual tokens into the trie, and put a reference of the document ID with every token (`{ key: 'hello', docs: [1] }`, which means: what are the documents containing the token `hello`?

You can see now that once you get the full `hello` token out of a trie, you can access all the documents containing that specific token with ease. That's why we don't store entire phrases into the trie.

I hope this clarifies a bit!

**Comment by nasainsbury** [comment]
Hey, thanks for that explanation, really helpful 👍 

Will close this issue, hopefully it will help someone else too :)
